name: mubadarah-dev
services:
  api:
    user: '1000:1000'
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:3000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads-dev:/app/uploads
    command: npm run start:debug